// <auto-generated />
namespace Playground.Mvc.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class smsisselected : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(smsisselected));
        
        string IMigrationMetadata.Id
        {
            get { return "201505060626188_sms-is-selected"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
